
[build]
  command = "npm run start"
  publish = "public"
  functions = "functions"

# Include all files in all functions
[functions]
  included_files = ["data/**.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/"
  status = 200
  force = true